import { Check, Close } from "@mui/icons-material";
import { GridColDef } from "@mui/x-data-grid";

export const mDoctorsColumns: GridColDef<TDoctorData>[] = [
  { field: "id", headerName: "ID", flex: 0.5 },
  {
    field: "name",
    headerName: "Name",
    flex: 1.5,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1.5,
  },
  {
    field: "phone",
    headerName: "Phone",
    flex: 1,
  },
  {
    field: "specialty",
    headerName: "Specialty",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "hourlyRate",
    flex: 1,
    headerName: "Hourly Rate",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "available",
    headerName: "Available",
    width: 90,
    align: "center",
    headerAlign: "center",
    renderCell: (params) => (params.value ? <Check color="success" /> : <Close color="error" />),
  },
  {
    field: "workingDays",
    headerName: "Working Days",
    flex: 2,
  },
  {
    field: "actions",
    headerName: "Actions",
    flex: 2,
  },
];

export const mDoctorsRows = [
  {
    id: 1,
    name: "Dr. João Silva",
    email: "joao.silva@medico.com",
    specialty: 1,
    phone: "(11) 98765-4321",
    available: false,
    hourlyRate: 150,
    workingDays: ["Segunda", "Terça", "Quarta"],
    actions: "",
  },
  {
    id: 2,
    name: "Dra. Maria Santos",
    email: "maria.santos@medico.com",
    specialty: 2,
    phone: "(11) 98765-1234",
    available: true,
    hourlyRate: 180,
    workingDays: ["Terça", "Quinta", "Sexta"],
    actions: "",
  },
  {
    id: 3,
    name: "Dr. Pedro Costa",
    email: "pedro.costa@medico.com",
    specialty: 3,
    phone: "(11) 98765-5678",
    available: true,
    hourlyRate: 200,
    workingDays: ["Segunda", "Quarta", "Sexta", "Sábado"],
    actions: "",
  },
  {
    id: 4,
    name: "Dra. Ana Oliveira",
    email: "ana.oliveira@medico.com",
    specialty: 4,
    phone: "(11) 98765-9999",
    available: true,
    hourlyRate: 170,
    workingDays: ["Segunda", "Terça", "Quinta"],
    actions: "",
  },
  {
    id: 5,
    name: "Dr. Carlos Mendes",
    email: "carlos.mendes@medico.com",
    specialty: 5,
    phone: "(11) 98765-7777",
    available: true,
    hourlyRate: 220,
    workingDays: ["Terça", "Quarta", "Quinta", "Sexta"],
    actions: "",
  },
  {
    id: 6,
    name: "Dr. Fernando Alves",
    email: "fernando.alves@medico.com",
    specialty: 2,
    phone: "(11) 98765-3333",
    available: true,
    hourlyRate: 175,
    workingDays: ["Segunda", "Quinta", "Sábado", "Domingo"],
    actions: "",
  },
  {
    id: 7,
    name: "Dra. Paula Costa",
    email: "paula.costa@medico.com",
    specialty: 6,
    phone: "(11) 98765-2222",
    available: true,
    hourlyRate: 190,
    workingDays: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
    actions: "",
  },
  {
    id: 8,
    name: "Dr. Roberto Lima",
    email: "roberto.lima@medico.com",
    specialty: 7,
    phone: "(11) 98765-8888",
    available: true,
    hourlyRate: 210,
    workingDays: ["Quarta", "Quinta", "Sexta", "Sábado"],
    actions: "",
  },
  {
    id: 9,
    name: "Dra. Juliana Pereira",
    email: "juliana.pereira@medico.com",
    specialty: 8,
    phone: "(11) 98765-6666",
    available: true,
    hourlyRate: 185,
    workingDays: ["Segunda", "Terça", "Quinta", "Sexta"],
    actions: "",
  },
  {
    id: 10,
    name: "Dr. Marcelo Santos",
    email: "marcelo.santos@medico.com",
    specialty: 9,
    phone: "(11) 98765-1111",
    available: true,
    hourlyRate: 195,
    workingDays: ["Terça", "Quarta", "Quinta", "Sábado", "Domingo"],
    actions: "",
  },
];

export type TDoctorData = (typeof mDoctorsRows)[number];
